version: "3.3"

#Define services
services:

  #MySql Database for application
  mysql-db:
    image: mysql
    restart: always
    container_name: mysql-db
    #Environment variable for password and default database
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'forum'
    ports:
      - 3306:3306
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

  #MySql Web UI
  php-my-admin:
    image: phpmyadmin
    restart: always
    container_name: php-my-admin
    ports:
      - 8081:80
    environment:        
      PMA_HOST: mysql-db

  #Back-end Spring Boot Application
  #springboot-app:
  #  build: ./forum
  #  container_name: springboot-app
    #Environment variable for Spring Boot Application.
  #  environment:
  #    MYSQL_HOST: 'mysql-db'
  #    MYSQL_USER: 'root'
  #    MYSQL_PASSWORD: 'password'
  #    MYSQL_DATABASE: 'forum'
  #  ports:
  #   - 8080:8080 #Forwars the exposed port 8080 on the container to port 8080 on the host machine
  #  links:
  #    - mysql-db

  #Front-end Angular Application
  #angular-app:
  #  build: ./forum-front
  #  container_name: angular-app
  #  ports:
  #    - 4200:4200 #Forwars the exposed port 4200 on the container to port 4200 on the host machine
  #  links:
  #    - springboot-app